
NBA_TEAMS = {
    # Eastern Conference
    'Cavaliers': {
        'name': 'Cleveland Cavaliers',
        'short_name': 'CLE',
        'division': 'Central',
        'logo_path': 'images/nba/cavaliers.png',
        'wins': 62,
        'losses': 16,
        'win_pct': .795,
        'games_back': 0,
        'home_record': '33-6',
        'away_record': '29-10',
        'div_record': '11-2',
        'conf_record': '39-9',
        'ppg': 122.1,
        'opp_ppg': 112.3,
        'diff': '+9.8',
        'streak': 'L1',
        'last_10': '6-4',
        'playoff_status': 'y'  # Clinched division
    },
    'Celtics': {
        'name': 'Boston Celtics',
        'short_name': 'BOS',
        'division': 'Atlantic',
        'logo_path': 'images/nba/celtics.png',
        'wins': 58,
        'losses': 20,
        'win_pct': .744,
        'games_back': 4,
        'home_record': '26-13',
        'away_record': '32-7',
        'div_record': '13-2',
        'conf_record': '36-12',
        'ppg': 116.9,
        'opp_ppg': 107.6,
        'diff': '+9.3',
        'streak': 'W2',
        'last_10': '9-1',
        'playoff_status': 'y'  # Clinched division
    },
    'Knicks': {
        'name': 'New York Knicks',
        'short_name': 'NY',
        'division': 'Atlantic',
        'logo_path': 'images/nba/knicks.png',
        'wins': 50,
        'losses': 28,
        'win_pct': .641,
        'games_back': 12,
        'home_record': '27-12',
        'away_record': '23-16',
        'div_record': '11-3',
        'conf_record': '33-15',
        'ppg': 116.1,
        'opp_ppg': 111.7,
        'diff': '+4.4',
        'streak': 'W2',
        'last_10': '7-3',
        'playoff_status': 'x'  # Clinched playoff
    },
    'Pacers': {
        'name': 'Indiana Pacers',
        'short_name': 'IND',
        'division': 'Central',
        'logo_path': 'images/nba/pacers.png',
        'wins': 47,
        'losses': 31,
        'win_pct': .603,
        'games_back': 15,
        'home_record': '27-10',
        'away_record': '19-20',
        'div_record': '8-6',
        'conf_record': '26-21',
        'ppg': 117.5,
        'opp_ppg': 115.2,
        'diff': '+2.3',
        'streak': 'W4',
        'last_10': '8-2',
        'playoff_status': 'x'  # Clinched playoff
    },
    'Bucks': {
        'name': 'Milwaukee Bucks',
        'short_name': 'MIL',
        'division': 'Central',
        'logo_path': 'images/nba/bucks.png',
        'wins': 44,
        'losses': 34,
        'win_pct': .564,
        'games_back': 18,
        'home_record': '24-14',
        'away_record': '19-20',
        'div_record': '7-7',
        'conf_record': '29-21',
        'ppg': 114.9,
        'opp_ppg': 112.9,
        'diff': '+2.0',
        'streak': 'W4',
        'last_10': '6-4',
        'playoff_status': 'x'  # Clinched playoff
    },
    'Pistons': {
        'name': 'Detroit Pistons',
        'short_name': 'DET',
        'division': 'Central',
        'logo_path': 'images/nba/pistons.png',
        'wins': 43,
        'losses': 35,
        'win_pct': .551,
        'games_back': 19,
        'home_record': '21-17',
        'away_record': '22-18',
        'div_record': '5-9',
        'conf_record': '28-21',
        'ppg': 115.2,
        'opp_ppg': 113.0,
        'diff': '+2.2',
        'streak': 'L1',
        'last_10': '6-4',
        'playoff_status': 'x'  # Clinched playoff
    },
    'Magic': {
        'name': 'Orlando Magic',
        'short_name': 'ORL',
        'division': 'Southeast',
        'logo_path': 'images/nba/magic.png',
        'wins': 38,
        'losses': 40,
        'win_pct': .487,
        'games_back': 24,
        'home_record': '20-19',
        'away_record': '18-21',
        'div_record': '11-3',
        'conf_record': '28-20',
        'ppg': 105.1,
        'opp_ppg': 105.6,
        'diff': '-0.5',
        'streak': 'W2',
        'last_10': '7-3',
        'playoff_status': 'pb'  # Play-in berth
    },
    'Hawks': {
        'name': 'Atlanta Hawks',
        'short_name': 'ATL',
        'division': 'Southeast',
        'logo_path': 'images/nba/hawks.png',
        'wins': 37,
        'losses': 41,
        'win_pct': .474,
        'games_back': 25,
        'home_record': '20-19',
        'away_record': '17-21',
        'div_record': '9-5',
        'conf_record': '27-21',
        'ppg': 118.0,
        'opp_ppg': 119.8,
        'diff': '-1.8',
        'streak': 'W1',
        'last_10': '5-5',
        'playoff_status': 'pb'  # Play-in berth
    },
    'Bulls': {
        'name': 'Chicago Bulls',
        'short_name': 'CHI',
        'division': 'Central',
        'logo_path': 'images/nba/bulls.png',
        'wins': 36,
        'losses': 42,
        'win_pct': .462,
        'games_back': 26,
        'home_record': '16-23',
        'away_record': '20-19',
        'div_record': '4-11',
        'conf_record': '25-23',
        'ppg': 117.8,
        'opp_ppg': 119.9,
        'diff': '-2.1',
        'streak': 'W3',
        'last_10': '7-3',
        'playoff_status': 'pb'  # Play-in berth
    },
    'Heat': {
        'name': 'Miami Heat',
        'short_name': 'MIA',
        'division': 'Southeast',
        'logo_path': 'images/nba/heat.png',
        'wins': 35,
        'losses': 43,
        'win_pct': .449,
        'games_back': 27,
        'home_record': '18-21',
        'away_record': '16-22',
        'div_record': '10-5',
        'conf_record': '23-26',
        'ppg': 109.9,
        'opp_ppg': 109.9,
        'diff': '0.0',
        'streak': 'L2',
        'last_10': '6-4',
        'playoff_status': 'pb'  # Play-in berth
    },
    'Raptors': {
        'name': 'Toronto Raptors',
        'short_name': 'TOR',
        'division': 'Atlantic',
        'logo_path': 'images/nba/raptors.png',
        'wins': 29,
        'losses': 50,
        'win_pct': .367,
        'games_back': 33.5,
        'home_record': '17-23',
        'away_record': '12-27',
        'div_record': '8-8',
        'conf_record': '20-31',
        'ppg': 110.7,
        'opp_ppg': 115.2,
        'diff': '-4.5',
        'streak': 'W1',
        'last_10': '5-5',
        'playoff_status': 'e'  # Eliminated
    },
    'Nets': {
        'name': 'Brooklyn Nets',
        'short_name': 'BKN',
        'division': 'Atlantic',
        'logo_path': 'images/nba/nets.png',
        'wins': 25,
        'losses': 53,
        'win_pct': .321,
        'games_back': 37,
        'home_record': '11-27',
        'away_record': '14-26',
        'div_record': '3-12',
        'conf_record': '14-35',
        'ppg': 105.1,
        'opp_ppg': 111.9,
        'diff': '-6.8',
        'streak': 'L2',
        'last_10': '2-8',
        'playoff_status': 'e'  # Eliminated
    },
    '76ers': {
        'name': 'Philadelphia 76ers',
        'short_name': 'PHI',
        'division': 'Atlantic',
        'logo_path': 'images/nba/76ers.png',
        'wins': 23,
        'losses': 55,
        'win_pct': .295,
        'games_back': 39,
        'home_record': '12-27',
        'away_record': '11-28',
        'div_record': '3-13',
        'conf_record': '14-34',
        'ppg': 109.6,
        'opp_ppg': 115.8,
        'diff': '-6.2',
        'streak': 'L11',
        'last_10': '0-10',
        'playoff_status': 'e'  # Eliminated
    },
    'Hornets': {
        'name': 'Charlotte Hornets',
        'short_name': 'CHA',
        'division': 'Southeast',
        'logo_path': 'images/nba/hornets.png',
        'wins': 19,
        'losses': 59,
        'win_pct': .244,
        'games_back': 43,
        'home_record': '12-28',
        'away_record': '7-31',
        'div_record': '1-15',
        'conf_record': '10-39',
        'ppg': 105.7,
        'opp_ppg': 114.0,
        'diff': '-8.3',
        'streak': 'L3',
        'last_10': '2-8',
        'playoff_status': 'e'  # Eliminated
    },
    'Wizards': {
        'name': 'Washington Wizards',
        'short_name': 'WSH',
        'division': 'Southeast',
        'logo_path': 'images/nba/wizards.png',
        'wins': 17,
        'losses': 61,
        'win_pct': .218,
        'games_back': 45,
        'home_record': '8-31',
        'away_record': '9-29',
        'div_record': '6-9',
        'conf_record': '12-36',
        'ppg': 108.3,
        'opp_ppg': 120.7,
        'diff': '-12.4',
        'streak': 'L2',
        'last_10': '2-8',
        'playoff_status': 'e'  # Eliminated
    },

    # Western Conference
    'Thunder': {
        'name': 'Oklahoma City Thunder',
        'short_name': 'OKC',
        'division': 'Northwest',
        'logo_path': 'images/nba/thunder.png',
        'wins': 64,
        'losses': 14,
        'win_pct': .821,
        'games_back': 0,
        'home_record': '34-6',
        'away_record': '29-8',
        'div_record': '11-4',
        'conf_record': '35-13',
        'ppg': 120.0,
        'opp_ppg': 107.5,
        'diff': '+12.5',
        'streak': 'L2',
        'last_10': '8-2',
        'playoff_status': 'z'  # Clinched conference
    },
    'Rockets': {
        'name': 'Houston Rockets',
        'short_name': 'HOU',
        'division': 'Southwest',
        'logo_path': 'images/nba/rockets.png',
        'wins': 52,
        'losses': 27,
        'win_pct': .658,
        'games_back': 12.5,
        'home_record': '29-11',
        'away_record': '23-15',
        'div_record': '13-3',
        'conf_record': '31-18',
        'ppg': 114.4,
        'opp_ppg': 108.9,
        'diff': '+5.5',
        'streak': 'W3',
        'last_10': '8-2',
        'playoff_status': 'y'  # Clinched division
    },
    'Lakers': {
        'name': 'Los Angeles Lakers',
        'short_name': 'LAL',
        'division': 'Pacific',
        'logo_path': 'images/nba/lakers.png',
        'wins': 48,
        'losses': 30,
        'win_pct': .615,
        'games_back': 16,
        'home_record': '30-10',
        'away_record': '18-20',
        'div_record': '12-4',
        'conf_record': '34-14',
        'ppg': 113.4,
        'opp_ppg': 112.1,
        'diff': '+1.3',
        'streak': 'W2',
        'last_10': '5-5',
        'playoff_status': ''  # Play-in tournament
    },
    'Nuggets': {
        'name': 'Denver Nuggets',
        'short_name': 'DEN',
        'division': 'Northwest',
        'logo_path': 'images/nba/nuggets.png',
        'wins': 47,
        'losses': 32,
        'win_pct': .595,
        'games_back': 17.5,
        'home_record': '25-15',
        'away_record': '22-17',
        'div_record': '8-8',
        'conf_record': '29-20',
        'ppg': 120.7,
        'opp_ppg': 117.1,
        'diff': '+3.6',
        'streak': 'L4',
        'last_10': '3-7',
        'playoff_status': ''  # Play-in tournament
    },
    'Clippers': {
        'name': 'LA Clippers',
        'short_name': 'LAC',
        'division': 'Pacific',
        'logo_path': 'images/nba/clippers.png',
        'wins': 46,
        'losses': 32,
        'win_pct': .590,
        'games_back': 18,
        'home_record': '28-11',
        'away_record': '18-21',
        'div_record': '7-7',
        'conf_record': '25-23',
        'ppg': 112.5,
        'opp_ppg': 108.0,
        'diff': '+4.5',
        'streak': 'W4',
        'last_10': '8-2',
        'playoff_status': ''  # Play-in tournament
    },
    'Warriors': {
        'name': 'Golden State Warriors',
        'short_name': 'GS',
        'division': 'Pacific',
        'logo_path': 'images/nba/warriors.png',
        'wins': 46,
        'losses': 32,
        'win_pct': .590,
        'games_back': 18,
        'home_record': '24-15',
        'away_record': '22-17',
        'div_record': '4-10',
        'conf_record': '27-21',
        'ppg': 113.7,
        'opp_ppg': 110.8,
        'diff': '+2.9',
        'streak': 'L1',
        'last_10': '7-3',
        'playoff_status': ''  # Play-in tournament
    },
    'Timberwolves': {
        'name': 'Minnesota Timberwolves',
        'short_name': 'MIN',
        'division': 'Northwest',
        'logo_path': 'images/nba/timberwolves.png',
        'wins': 46,
        'losses': 32,
        'win_pct': .590,
        'games_back': 18,
        'home_record': '23-16',
        'away_record': '23-16',
        'div_record': '10-5',
        'conf_record': '31-19',
        'ppg': 114.0,
        'opp_ppg': 109.4,
        'diff': '+4.6',
        'streak': 'W5',
        'last_10': '7-3',
        'playoff_status': ''  # Play-in tournament
    },
    'Grizzlies': {
        'name': 'Memphis Grizzlies',
        'short_name': 'MEM',
        'division': 'Southwest',
        'logo_path': 'images/nba/grizzlies.png',
        'wins': 46,
        'losses': 32,
        'win_pct': .590,
        'games_back': 18,
        'home_record': '25-14',
        'away_record': '21-18',
        'div_record': '10-5',
        'conf_record': '26-22',
        'ppg': 121.7,
        'opp_ppg': 117.0,
        'diff': '+4.7',
        'streak': 'W2',
        'last_10': '3-7',
        'playoff_status': ''  # Play-in tournament
    },
    'Kings': {
        'name': 'Sacramento Kings',
        'short_name': 'SAC',
        'division': 'Pacific',
        'logo_path': 'images/nba/kings.png',
        'wins': 38,
        'losses': 40,
        'win_pct': .487,
        'games_back': 26,
        'home_record': '19-19',
        'away_record': '19-21',
        'div_record': '4-10',
        'conf_record': '25-24',
        'ppg': 115.9,
        'opp_ppg': 115.5,
        'diff': '+0.4',
        'streak': 'W2',
        'last_10': '3-7',
        'playoff_status': ''  # Play-in tournament
    },
    'Mavericks': {
        'name': 'Dallas Mavericks',
        'short_name': 'DAL',
        'division': 'Southwest',
        'logo_path': 'images/nba/mavericks.png',
        'wins': 38,
        'losses': 41,
        'win_pct': .481,
        'games_back': 26.5,
        'home_record': '21-17',
        'away_record': '17-24',
        'div_record': '8-7',
        'conf_record': '23-27',
        'ppg': 114.5,
        'opp_ppg': 115.4,
        'diff': '-0.9',
        'streak': 'L2',
        'last_10': '5-5',
        'playoff_status': ''  # Play-in tournament
    },
    'Suns': {
        'name': 'Phoenix Suns',
        'short_name': 'PHX',
        'division': 'Pacific',
        'logo_path': 'images/nba/suns.png',
        'wins': 35,
        'losses': 43,
        'win_pct': .449,
        'games_back': 29,
        'home_record': '23-15',
        'away_record': '12-28',
        'div_record': '9-5',
        'conf_record': '21-27',
        'ppg': 114.0,
        'opp_ppg': 116.6,
        'diff': '-2.6',
        'streak': 'L6',
        'last_10': '4-6',
        'playoff_status': 'e'  # Eliminated
    },
    'Trail Blazers': {
        'name': 'Portland Trail Blazers',
        'short_name': 'POR',
        'division': 'Northwest',
        'logo_path': 'images/nba/blazers.png',
        'wins': 35,
        'losses': 44,
        'win_pct': .443,
        'games_back': 29.5,
        'home_record': '21-18',
        'away_record': '14-26',
        'div_record': '6-9',
        'conf_record': '18-31',
        'ppg': 111.0,
        'opp_ppg': 114.2,
        'diff': '-3.2',
        'streak': 'W1',
        'last_10': '5-5',
        'playoff_status': 'e'  # Eliminated
    },
    'Spurs': {
        'name': 'San Antonio Spurs',
        'short_name': 'SA',
        'division': 'Southwest',
        'logo_path': 'images/nba/spurs.png',
        'wins': 32,
        'losses': 46,
        'win_pct': .410,
        'games_back': 32,
        'home_record': '19-20',
        'away_record': '12-25',
        'div_record': '5-11',
        'conf_record': '21-28',
        'ppg': 113.9,
        'opp_ppg': 116.7,
        'diff': '-2.8',
        'streak': 'L2',
        'last_10': '3-7',
        'playoff_status': 'e'  # Eliminated
    },
    'Pelicans': {
        'name': 'New Orleans Pelicans',
        'short_name': 'NO',
        'division': 'Southwest',
        'logo_path': 'images/nba/pelicans.png',
        'wins': 21,
        'losses': 57,
        'win_pct': .269,
        'games_back': 43,
        'home_record': '14-25',
        'away_record': '7-32',
        'div_record': '3-13',
        'conf_record': '13-37',
        'ppg': 110.0,
        'opp_ppg': 118.7,
        'diff': '-8.7',
        'streak': 'L3',
        'last_10': '3-7',
        'playoff_status': 'e'  # Eliminated
    },
    'Jazz': {
        'name': 'Utah Jazz',
        'short_name': 'UTAH',
        'division': 'Northwest',
        'logo_path': 'images/nba/jazz.png',
        'wins': 16,
        'losses': 63,
        'win_pct': .203,
        'games_back': 48.5,
        'home_record': '9-30',
        'away_record': '7-33',
        'div_record': '2-11',
        'conf_record': '7-42',
        'ppg': 111.7,
        'opp_ppg': 120.9,
        'diff': '-9.2',
        'streak': 'L9',
        'last_10': '1-9',
        'playoff_status': 'e'  # Eliminated
    }
}

NBA_DIVISIONS = {
    'Atlantic': ['Celtics', 'Knicks', '76ers', 'Nets', 'Raptors'],
    'Central': ['Cavaliers', 'Bucks', 'Pacers', 'Bulls', 'Pistons'],
    'Southeast': ['Heat', 'Hawks', 'Magic', 'Hornets', 'Wizards'],
    'Northwest': ['Thunder', 'Nuggets', 'Timberwolves', 'Jazz', 'Trail Blazers'],
    'Pacific': ['Lakers', 'Clippers', 'Suns', 'Warriors', 'Kings'],
    'Southwest': ['Rockets', 'Mavericks', 'Grizzlies', 'Pelicans', 'Spurs']
}

MLB_TEAMS = {
    # American League East
    'Yankees': {
        'name': 'New York Yankees',
        'short_name': 'NYY',
        'division': 'AL East',
        'conference': 'American League',
        'logo_path': 'images/mlb/yankees.png',
        'wins': 6,
        'losses': 4,
        'win_pct': .600,
        'gb': '-',
        'home_record': '4-2',
        'away_record': '2-2',
        'runs_scored': 78,
        'runs_against': 51,
        'run_diff': '+27',
        'streak': 'L2',
        'last_10': '6-4'
    },
    'Blue Jays': {
        'name': 'Toronto Blue Jays',
        'short_name': 'TOR',
        'division': 'AL East',
        'conference': 'American League',
        'logo_path': 'images/mlb/bluejays.png',
        'wins': 6,
        'losses': 5,
        'win_pct': .545,
        'gb': '0.5',
        'home_record': '5-2',
        'away_record': '1-3',
        'runs_scored': 41,
        'runs_against': 43,
        'run_diff': '-2',
        'streak': 'W1',
        'last_10': '6-4'
    },
    'Red Sox': {
        'name': 'Boston Red Sox',
        'short_name': 'BOS',
        'division': 'AL East',
        'conference': 'American League',
        'logo_path': 'images/mlb/redsox.png',
        'wins': 6,
        'losses': 5,
        'win_pct': .545,
        'gb': '0.5',
        'home_record': '3-1',
        'away_record': '3-4',
        'runs_scored': 65,
        'runs_against': 51,
        'run_diff': '+14',
        'streak': 'L1',
        'last_10': '5-5'
    },
    'Rays': {
        'name': 'Tampa Bay Rays',
        'short_name': 'TB',
        'division': 'AL East',
        'conference': 'American League',
        'logo_path': 'images/mlb/rays.png',
        'wins': 4,
        'losses': 5,
        'win_pct': .444,
        'gb': '1.5',
        'home_record': '4-2',
        'away_record': '0-3',
        'runs_scored': 34,
        'runs_against': 28,
        'run_diff': '+6',
        'streak': 'L4',
        'last_10': '4-5'
    },
    'Orioles': {
        'name': 'Baltimore Orioles',
        'short_name': 'BAL',
        'division': 'AL East',
        'conference': 'American League',
        'logo_path': 'images/mlb/orioles.png',
        'wins': 4,
        'losses': 6,
        'win_pct': .400,
        'gb': '2',
        'home_record': '1-2',
        'away_record': '3-4',
        'runs_scored': 47,
        'runs_against': 47,
        'run_diff': '0',
        'streak': 'L1',
        'last_10': '4-6'
    },

    # American League Central
    'Tigers': {
        'name': 'Detroit Tigers',
        'short_name': 'DET',
        'division': 'AL Central',
        'conference': 'American League',
        'logo_path': 'images/mlb/tigers.png',
        'wins': 6,
        'losses': 4,
        'win_pct': .600,
        'gb': '-',
        'home_record': '4-0',
        'away_record': '2-4',
        'runs_scored': 51,
        'runs_against': 41,
        'run_diff': '+10',
        'streak': 'W4',
        'last_10': '6-4'
    },
    'Royals': {
        'name': 'Kansas City Royals',
        'short_name': 'KC',
        'division': 'AL Central',
        'conference': 'American League',
        'logo_path': 'images/mlb/royals.png',
        'wins': 4,
        'losses': 5,
        'win_pct': .444,
        'gb': '1.5',
        'home_record': '3-3',
        'away_record': '1-2',
        'runs_scored': 36,
        'runs_against': 36,
        'run_diff': '0',
        'streak': 'W1',
        'last_10': '4-5'
    },
    'Twins': {
        'name': 'Minnesota Twins',
        'short_name': 'MIN',
        'division': 'AL Central',
        'conference': 'American League',
        'logo_path': 'images/mlb/twins.png',
        'wins': 3,
        'losses': 6,
        'win_pct': .333,
        'gb': '2.5',
        'home_record': '1-2',
        'away_record': '2-4',
        'runs_scored': 35,
        'runs_against': 47,
        'run_diff': '-12',
        'streak': 'L1',
        'last_10': '3-6'
    },
    'Guardians': {
        'name': 'Cleveland Guardians',
        'short_name': 'CLE',
        'division': 'AL Central',
        'conference': 'American League',
        'logo_path': 'images/mlb/guardians.png',
        'wins': 3,
        'losses': 6,
        'win_pct': .333,
        'gb': '2.5',
        'home_record': '0-0',
        'away_record': '3-6',
        'runs_scored': 34,
        'runs_against': 51,
        'run_diff': '-17',
        'streak': 'L2',
        'last_10': '3-6'
    },
    'White Sox': {
        'name': 'Chicago White Sox',
        'short_name': 'CHW',
        'division': 'AL Central',
        'conference': 'American League',
        'logo_path': 'images/mlb/whitesox.png',
        'wins': 2,
        'losses': 7,
        'win_pct': .222,
        'gb': '3.5',
        'home_record': '2-4',
        'away_record': '0-3',
        'runs_scored': 32,
        'runs_against': 37,
        'run_diff': '-5',
        'streak': 'L5',
        'last_10': '2-7'
    },

    # American League West
    'Rangers': {
        'name': 'Texas Rangers',
        'short_name': 'TEX',
        'division': 'AL West',
        'conference': 'American League',
        'logo_path': 'images/mlb/rangers.png',
        'wins': 8,
        'losses': 3,
        'win_pct': .727,
        'gb': '-',
        'home_record': '6-1',
        'away_record': '2-2',
        'runs_scored': 33,
        'runs_against': 41,
        'run_diff': '-8',
        'streak': 'L1',
        'last_10': '8-2'
    },
    'Angels': {
        'name': 'Los Angeles Angels',
        'short_name': 'LAA',
        'division': 'AL West',
        'conference': 'American League',
        'logo_path': 'images/mlb/angels.png',
        'wins': 6,
        'losses': 3,
        'win_pct': .667,
        'gb': '1',
        'home_record': '2-1',
        'away_record': '4-2',
        'runs_scored': 46,
        'runs_against': 47,
        'run_diff': '-1',
        'streak': 'W2',
        'last_10': '6-3'
    },
    'Astros': {
        'name': 'Houston Astros',
        'short_name': 'HOU',
        'division': 'AL West',
        'conference': 'American League',
        'logo_path': 'images/mlb/astros.png',
        'wins': 4,
        'losses': 5,
        'win_pct': .444,
        'gb': '3',
        'home_record': '2-4',
        'away_record': '2-1',
        'runs_scored': 27,
        'runs_against': 36,
        'run_diff': '-9',
        'streak': 'W1',
        'last_10': '4-5'
    },
    'Athletics': {
        'name': 'Oakland Athletics',
        'short_name': 'OAK',
        'division': 'AL West',
        'conference': 'American League',
        'logo_path': 'images/mlb/athletics.png',
        'wins': 4,
        'losses': 6,
        'win_pct': .400,
        'gb': '3.5',
        'home_record': '0-3',
        'away_record': '4-3',
        'runs_scored': 41,
        'runs_against': 62,
        'run_diff': '-21',
        'streak': 'L1',
        'last_10': '4-6'
    },
    'Mariners': {
        'name': 'Seattle Mariners',
        'short_name': 'SEA',
        'division': 'AL West',
        'conference': 'American League',
        'logo_path': 'images/mlb/mariners.png',
        'wins': 3,
        'losses': 7,
        'win_pct': .300,
        'gb': '4.5',
        'home_record': '3-4',
        'away_record': '0-3',
        'runs_scored': 32,
        'runs_against': 48,
        'run_diff': '-16',
        'streak': 'L3',
        'last_10': '3-7'
    },

    # National League East
    'Phillies': {
        'name': 'Philadelphia Phillies',
        'short_name': 'PHI',
        'division': 'NL East',
        'conference': 'National League',
        'logo_path': 'images/mlb/phillies.png',
        'wins': 7,
        'losses': 2,
        'win_pct': .778,
        'gb': '-',
        'home_record': '5-1',
        'away_record': '2-1',
        'runs_scored': 45,
        'runs_against': 29,
        'run_diff': '+16',
        'streak': 'W1',
        'last_10': '7-2'
    },
    'Mets': {
        'name': 'New York Mets',
        'short_name': 'NYM',
        'division': 'NL East',
        'conference': 'National League',
        'logo_path': 'images/mlb/mets.png',
        'wins': 7,
        'losses': 3,
        'win_pct': .700,
        'gb': '0.5',
        'home_record': '4-0',
        'away_record': '3-3',
        'runs_scored': 35,
        'runs_against': 22,
        'run_diff': '+13',
        'streak': 'W5',
        'last_10': '7-3'
    },
    'Marlins': {
        'name': 'Miami Marlins',
        'short_name': 'MIA',
        'division': 'NL East',
        'conference': 'National League',
        'logo_path': 'images/mlb/marlins.png',
        'wins': 5,
        'losses': 5,
        'win_pct': .500,
        'gb': '2.5',
        'home_record': '4-3',
        'away_record': '1-2',
        'runs_scored': 33,
        'runs_against': 44,
        'run_diff': '-11',
        'streak': 'L1',
        'last_10': '5-5'
    },
    'Nationals': {
        'name': 'Washington Nationals',
        'short_name': 'WSH',
        'division': 'NL East',
        'conference': 'National League',
        'logo_path': 'images/mlb/nationals.png',
        'wins': 4,
        'losses': 6,
        'win_pct': .400,
        'gb': '3.5',
        'home_record': '4-3',
        'away_record': '0-3',
        'runs_scored': 40,
        'runs_against': 50,
        'run_diff': '-10',
        'streak': 'W3',
        'last_10': '4-6'
    },
    'Braves': {
        'name': 'Atlanta Braves',
        'short_name': 'ATL',
        'division': 'NL East',
        'conference': 'National League',
        'logo_path': 'images/mlb/braves.png',
        'wins': 1,
        'losses': 8,
        'win_pct': .111,
        'gb': '6',
        'home_record': '1-1',
        'away_record': '0-7',
        'runs_scored': 24,
        'runs_against': 36,
        'run_diff': '-12',
        'streak': 'L1',
        'last_10': '1-8'
    },

    # National League Central
    'Cubs': {
        'name': 'Chicago Cubs',
        'short_name': 'CHC',
        'division': 'NL Central',
        'conference': 'National League',
        'logo_path': 'images/mlb/cubs.png',
        'wins': 8,
        'losses': 5,
        'win_pct': .615,
        'gb': '-',
        'home_record': '3-3',
        'away_record': '5-2',
        'runs_scored': 84,
        'runs_against': 56,
        'run_diff': '+28',
        'streak': 'W1',
        'last_10': '7-3'
    },
    'Brewers': {
        'name': 'Milwaukee Brewers',
        'short_name': 'MIL',
        'division': 'NL Central',
        'conference': 'National League',
        'logo_path': 'images/mlb/brewers.png',
        'wins': 5,
        'losses': 5,
        'win_pct': .500,
        'gb': '1.5',
        'home_record': '5-2',
        'away_record': '0-3',
        'runs_scored': 42,
        'runs_against': 64,
        'run_diff': '-22',
        'streak': 'W1',
        'last_10': '5-5'
    },
    'Cardinals': {
        'name': 'St. Louis Cardinals',
        'short_name': 'STL',
        'division': 'NL Central',
        'conference': 'National League',
        'logo_path': 'images/mlb/cardinals.png',
        'wins': 4,
        'losses': 6,
        'win_pct': .400,
        'gb': '2.5',
        'home_record': '4-2',
        'away_record': '0-4',
        'runs_scored': 66,
        'runs_against': 69,
        'run_diff': '-3',
        'streak': 'L4',
        'last_10': '4-6'
    },
    'Pirates': {
        'name': 'Pittsburgh Pirates',
        'short_name': 'PIT',
        'division': 'NL Central',
        'conference': 'National League',
        'logo_path': 'images/mlb/pirates.png',
        'wins': 4,
        'losses': 7,
        'win_pct': .364,
        'gb': '3',
        'home_record': '2-2',
        'away_record': '2-5',
        'runs_scored': 40,
        'runs_against': 58,
        'run_diff': '-18',
        'streak': 'W2',
        'last_10': '4-6'
    },
    'Reds': {
        'name': 'Cincinnati Reds',
        'short_name': 'CIN',
        'division': 'NL Central',
        'conference': 'National League',
        'logo_path': 'images/mlb/reds.png',
        'wins': 3,
        'losses': 7,
        'win_pct': .300,
        'gb': '3.5',
        'home_record': '2-4',
        'away_record': '1-3',
        'runs_scored': 39,
        'runs_against': 38,
        'run_diff': '+1',
        'streak': 'L1',
        'last_10': '3-7'
    },

    # National League West
    'Giants': {
        'name': 'San Francisco Giants',
        'short_name': 'SF',
        'division': 'NL West',
        'conference': 'National League',
        'logo_path': 'images/mlb/giants.png',
        'wins': 8,
        'losses': 1,
        'win_pct': .889,
        'gb': '-',
        'home_record': '3-0',
        'away_record': '5-1',
        'runs_scored': 49,
        'runs_against': 30,
        'run_diff': '+19',
        'streak': 'W7',
        'last_10': '8-1'
    },
    'Padres': {
        'name': 'San Diego Padres',
        'short_name': 'SD',
        'division': 'NL West',
        'conference': 'National League',
        'logo_path': 'images/mlb/padres.png',
        'wins': 8,
        'losses': 2,
        'win_pct': .800,
        'gb': '0.5',
        'home_record': '7-0',
        'away_record': '1-2',
        'runs_scored': 46,
        'runs_against': 28,
        'run_diff': '+18',
        'streak': 'W1',
        'last_10': '8-2'
    },
    'Dodgers': {
        'name': 'Los Angeles Dodgers',
        'short_name': 'LAD',
        'division': 'NL West',
        'conference': 'National League',
        'logo_path': 'images/mlb/dodgers.png',
        'wins': 9,
        'losses': 3,
        'win_pct': .750,
        'gb': '0.5',
        'home_record': '6-0',
        'away_record': '3-3',
        'runs_scored': 61,
        'runs_against': 41,
        'run_diff': '+20',
        'streak': 'L2',
        'last_10': '7-3'
    },
    'Diamondbacks': {
        'name': 'Arizona Diamondbacks',
        'short_name': 'ARI',
        'division': 'NL West',
        'conference': 'National League',
        'logo_path': 'images/mlb/diamondbacks.png',
        'wins': 5,
        'losses': 5,
        'win_pct': .500,
        'gb': '3.5',
        'home_record': '2-2',
        'away_record': '3-3',
        'runs_scored': 58,
        'runs_against': 51,
        'run_diff': '+7',
        'streak': 'L2',
        'last_10': '5-5'
    },
    'Rockies': {
        'name': 'Colorado Rockies',
        'short_name': 'COL',
        'division': 'NL West',
        'conference': 'National League',
        'logo_path': 'images/mlb/rockies.png',
        'wins': 2,
        'losses': 7,
        'win_pct': .222,
        'gb': '6',
        'home_record': '1-2',
        'away_record': '1-5',
        'runs_scored': 30,
        'runs_against': 42,
        'run_diff': '-12',
        'streak': 'W1',
        'last_10': '2-7'
    }
}

MLB_DIVISIONS = {
    'AL East': ['Yankees', 'Blue Jays', 'Red Sox', 'Rays', 'Orioles'],
    'AL Central': ['Tigers', 'Royals', 'Twins', 'Guardians', 'White Sox'],
    'AL West': ['Rangers', 'Angels', 'Astros', 'Athletics', 'Mariners'],
    'NL East': ['Phillies', 'Mets', 'Marlins', 'Nationals', 'Braves'],
    'NL Central': ['Cubs', 'Brewers', 'Cardinals', 'Pirates', 'Reds'],
    'NL West': ['Giants', 'Padres', 'Dodgers', 'Diamondbacks', 'Rockies']
}

NFL_TEAMS = {
    # AFC East
    'Bills': {
        'name': 'Buffalo Bills',
        'short_name': 'BUF',
        'division': 'AFC East',
        'conference': 'AFC',
        'logo_path': 'images/nfl/bills.png',
        'wins': 13,
        'losses': 4,
        'ties': 0,
        'win_pct': .765,
        'home_record': '8-0',
        'away_record': '5-4',
        'div_record': '5-1',
        'conf_record': '9-3',
        'points_for': 525,
        'points_against': 368,
        'point_diff': '+157',
        'streak': 'L1',
        'playoff_status': 'z'  # Clinched division
    },
    'Dolphins': {
        'name': 'Miami Dolphins',
        'short_name': 'MIA',
        'division': 'AFC East',
        'conference': 'AFC',
        'logo_path': 'images/nfl/dolphins.png',
        'wins': 8,
        'losses': 9,
        'ties': 0,
        'win_pct': .471,
        'home_record': '5-3',
        'away_record': '3-6',
        'div_record': '3-3',
        'conf_record': '6-6',
        'points_for': 345,
        'points_against': 364,
        'point_diff': '-19',
        'streak': 'L1',
        'playoff_status': 'e'  # Eliminated
    },
    'Jets': {
        'name': 'New York Jets',
        'short_name': 'NYJ',
        'division': 'AFC East',
        'conference': 'AFC',
        'logo_path': 'images/nfl/jets.png',
        'wins': 5,
        'losses': 12,
        'ties': 0,
        'win_pct': .294,
        'home_record': '3-5',
        'away_record': '2-7',
        'div_record': '2-4',
        'conf_record': '5-7',
        'points_for': 338,
        'points_against': 404,
        'point_diff': '-66',
        'streak': 'W1',
        'playoff_status': 'e'  # Eliminated
    },
    'Patriots': {
        'name': 'New England Patriots',
        'short_name': 'NE',
        'division': 'AFC East',
        'conference': 'AFC',
        'logo_path': 'images/nfl/patriots.png',
        'wins': 4,
        'losses': 13,
        'ties': 0,
        'win_pct': .235,
        'home_record': '2-6',
        'away_record': '2-7',
        'div_record': '2-4',
        'conf_record': '3-9',
        'points_for': 289,
        'points_against': 417,
        'point_diff': '-128',
        'streak': 'W1',
        'playoff_status': 'e'  # Eliminated
    },

    # AFC North
    'Ravens': {
        'name': 'Baltimore Ravens',
        'short_name': 'BAL',
        'division': 'AFC North',
        'conference': 'AFC',
        'logo_path': 'images/nfl/ravens.png',
        'wins': 12,
        'losses': 5,
        'ties': 0,
        'win_pct': .706,
        'home_record': '6-2',
        'away_record': '6-3',
        'div_record': '4-2',
        'conf_record': '8-4',
        'points_for': 518,
        'points_against': 361,
        'point_diff': '+157',
        'streak': 'W4',
        'playoff_status': 'z'  # Clinched division
    },
    'Steelers': {
        'name': 'Pittsburgh Steelers',
        'short_name': 'PIT',
        'division': 'AFC North',
        'conference': 'AFC',
        'logo_path': 'images/nfl/steelers.png',
        'wins': 10,
        'losses': 7,
        'ties': 0,
        'win_pct': .588,
        'home_record': '5-3',
        'away_record': '5-4',
        'div_record': '3-3',
        'conf_record': '7-5',
        'points_for': 380,
        'points_against': 347,
        'point_diff': '+33',
        'streak': 'L4',
        'playoff_status': 'y'  # Wild Card
    },
    'Bengals': {
        'name': 'Cincinnati Bengals',
        'short_name': 'CIN',
        'division': 'AFC North',
        'conference': 'AFC',
        'logo_path': 'images/nfl/bengals.png',
        'wins': 9,
        'losses': 8,
        'ties': 0,
        'win_pct': .529,
        'home_record': '3-5',
        'away_record': '6-3',
        'div_record': '3-3',
        'conf_record': '6-6',
        'points_for': 472,
        'points_against': 434,
        'point_diff': '+38',
        'streak': 'W5',
        'playoff_status': 'e'  # Eliminated
    },
    'Browns': {
        'name': 'Cleveland Browns',
        'short_name': 'CLE',
        'division': 'AFC North',
        'conference': 'AFC',
        'logo_path': 'images/nfl/browns.png',
        'wins': 3,
        'losses': 14,
        'ties': 0,
        'win_pct': .176,
        'home_record': '2-6',
        'away_record': '1-8',
        'div_record': '2-4',
        'conf_record': '3-9',
        'points_for': 258,
        'points_against': 435,
        'point_diff': '-177',
        'streak': 'L6',
        'playoff_status': 'e'  # Eliminated
    },

    # AFC South
    'Texans': {
        'name': 'Houston Texans',
        'short_name': 'HOU',
        'division': 'AFC South',
        'conference': 'AFC',
        'logo_path': 'images/nfl/texans.png',
        'wins': 10,
        'losses': 7,
        'ties': 0,
        'win_pct': .588,
        'home_record': '5-3',
        'away_record': '5-4',
        'div_record': '5-1',
        'conf_record': '8-4',
        'points_for': 372,
        'points_against': 372,
        'point_diff': '0',
        'streak': 'W1',
        'playoff_status': 'z'  # Clinched division
    },
    'Colts': {
        'name': 'Indianapolis Colts',
        'short_name': 'IND',
        'division': 'AFC South',
        'conference': 'AFC',
        'logo_path': 'images/nfl/colts.png',
        'wins': 8,
        'losses': 9,
        'ties': 0,
        'win_pct': .471,
        'home_record': '5-3',
        'away_record': '3-6',
        'div_record': '3-3',
        'conf_record': '7-5',
        'points_for': 377,
        'points_against': 427,
        'point_diff': '-50',
        'streak': 'W1',
        'playoff_status': 'e'  # Eliminated
    },
    'Jaguars': {
        'name': 'Jacksonville Jaguars',
        'short_name': 'JAX',
        'division': 'AFC South',
        'conference': 'AFC',
        'logo_path': 'images/nfl/jaguars.png',
        'wins': 4,
        'losses': 13,
        'ties': 0,
        'win_pct': .235,
        'home_record': '3-5',
        'away_record': '1-8',
        'div_record': '3-3',
        'conf_record': '4-8',
        'points_for': 320,
        'points_against': 435,
        'point_diff': '-115',
        'streak': 'L1',
        'playoff_status': 'e'  # Eliminated
    },
    'Titans': {
        'name': 'Tennessee Titans',
        'short_name': 'TEN',
        'division': 'AFC South',
        'conference': 'AFC',
        'logo_path': 'images/nfl/titans.png',
        'wins': 3,
        'losses': 14,
        'ties': 0,
        'win_pct': .176,
        'home_record': '1-7',
        'away_record': '2-7',
        'div_record': '1-5',
        'conf_record': '3-9',
        'points_for': 311,
        'points_against': 460,
        'point_diff': '-149',
        'streak': 'L6',
        'playoff_status': 'e'  # Eliminated
    },

    # AFC West
    'Chiefs': {
        'name': 'Kansas City Chiefs',
        'short_name': 'KC',
        'division': 'AFC West',
        'conference': 'AFC',
        'logo_path': 'images/nfl/chiefs.png',
        'wins': 15,
        'losses': 2,
        'ties': 0,
        'win_pct': .882,
        'home_record': '8-0',
        'away_record': '7-2',
        'div_record': '5-1',
        'conf_record': '10-2',
        'points_for': 385,
        'points_against': 326,
        'point_diff': '+59',
        'streak': 'L1',
        'playoff_status': '*'  # Clinched division and bye
    },
    'Chargers': {
        'name': 'Los Angeles Chargers',
        'short_name': 'LAC',
        'division': 'AFC West',
        'conference': 'AFC',
        'logo_path': 'images/nfl/chargers.png',
        'wins': 11,
        'losses': 6,
        'ties': 0,
        'win_pct': .647,
        'home_record': '5-3',
        'away_record': '6-3',
        'div_record': '4-2',
        'conf_record': '8-4',
        'points_for': 402,
        'points_against': 301,
        'point_diff': '+101',
        'streak': 'W3',
        'playoff_status': 'y'  # Wild Card
    },
    'Broncos': {
        'name': 'Denver Broncos',
        'short_name': 'DEN',
        'division': 'AFC West',
        'conference': 'AFC',
        'logo_path': 'images/nfl/broncos.png',
        'wins': 10,
        'losses': 7,
        'ties': 0,
        'win_pct': .588,
        'home_record': '6-2',
        'away_record': '4-5',
        'div_record': '3-3',
        'conf_record': '6-6',
        'points_for': 425,
        'points_against': 311,
        'point_diff': '+114',
        'streak': 'W1',
        'playoff_status': 'y'  # Wild Card
    },
    'Raiders': {
        'name': 'Las Vegas Raiders',
        'short_name': 'LV',
        'division': 'AFC West',
        'conference': 'AFC',
        'logo_path': 'images/nfl/raiders.png',
        'wins': 4,
        'losses': 13,
        'ties': 0,
        'win_pct': .235,
        'home_record': '2-6',
        'away_record': '2-7',
        'div_record': '0-6',
        'conf_record': '3-9',
        'points_for': 309,
        'points_against': 434,
        'point_diff': '-125',
        'streak': 'L1',
        'playoff_status': 'e'  # Eliminated
    },

    # NFC East
    'Eagles': {
        'name': 'Philadelphia Eagles',
        'short_name': 'PHI',
        'division': 'NFC East',
        'conference': 'NFC',
        'logo_path': 'images/nfl/eagles.png',
        'wins': 14,
        'losses': 3,
        'ties': 0,
        'win_pct': .824,
        'home_record': '8-1',
        'away_record': '6-2',
        'div_record': '5-1',
        'conf_record': '9-3',
        'points_for': 463,
        'points_against': 303,
        'point_diff': '+160',
        'streak': 'W2',
        'playoff_status': 'z'  # Clinched division
    },
    'Commanders': {
        'name': 'Washington Commanders',
        'short_name': 'WSH',
        'division': 'NFC East',
        'conference': 'NFC',
        'logo_path': 'images/nfl/commanders.png',
        'wins': 12,
        'losses': 5,
        'ties': 0,
        'win_pct': .706,
        'home_record': '7-2',
        'away_record': '5-3',
        'div_record': '4-2',
        'conf_record': '9-3',
        'points_for': 485,
        'points_against': 391,
        'point_diff': '+94',
        'streak': 'W5',
        'playoff_status': 'y'  # Wild Card
    },
    'Cowboys': {
        'name': 'Dallas Cowboys',
        'short_name': 'DAL',
        'division': 'NFC East',
        'conference': 'NFC',
        'logo_path': 'images/nfl/cowboys.png',
        'wins': 7,
        'losses': 10,
        'ties': 0,
        'win_pct': .412,
        'home_record': '2-7',
        'away_record': '5-3',
        'div_record': '3-3',
        'conf_record': '5-7',
        'points_for': 350,
        'points_against': 468,
        'point_diff': '-118',
        'streak': 'L2',
        'playoff_status': 'e'  # Eliminated
    },
    'Giants': {
        'name': 'New York Giants',
        'short_name': 'NYG',
        'division': 'NFC East',
        'conference': 'NFC',
        'logo_path': 'images/nfl/giants.png',
        'wins': 3,
        'losses': 14,
        'ties': 0,
        'win_pct': .176,
        'home_record': '1-8',
        'away_record': '2-6',
        'div_record': '0-6',
        'conf_record': '1-11',
        'points_for': 273,
        'points_against': 415,
        'point_diff': '-142',
        'streak': 'L1',
        'playoff_status': 'e'  # Eliminated
    },

    # NFC North
    'Lions': {
        'name': 'Detroit Lions',
        'short_name': 'DET',
        'division': 'NFC North',
        'conference': 'NFC',
        'logo_path': 'images/nfl/lions.png',
        'wins': 15,
        'losses': 2,
        'ties': 0,
        'win_pct': .882,
        'home_record': '7-2',
        'away_record': '8-0',
        'div_record': '6-0',
        'conf_record': '11-1',
        'points_for': 564,
        'points_against': 342,
        'point_diff': '+222',
        'streak': 'W3',
        'playoff_status': '*'  # Clinched division and bye
    },
    'Vikings': {
        'name': 'Minnesota Vikings',
        'short_name': 'MIN',
        'division': 'NFC North',
        'conference': 'NFC',
        'logo_path': 'images/nfl/vikings.png',
        'wins': 14,
        'losses': 3,
        'ties': 0,
        'win_pct': .824,
        'home_record': '8-1',
        'away_record': '6-2',
        'div_record': '4-2',
        'conf_record': '9-3',
        'points_for': 432,
        'points_against': 332,
        'point_diff': '+100',
        'streak': 'L1',
        'playoff_status': 'y'  # Wild Card
    },
    'Packers': {
        'name': 'Green Bay Packers',
        'short_name': 'GB',
        'division': 'NFC North',
        'conference': 'NFC',
        'logo_path': 'images/nfl/packers.png',
        'wins': 11,
        'losses': 6,
        'ties': 0,
        'win_pct': .647,
        'home_record': '6-3',
        'away_record': '5-3',
        'div_record': '1-5',
        'conf_record': '6-6',
        'points_for': 460,
        'points_against': 338,
        'point_diff': '+122',
        'streak': 'L2',
        'playoff_status': 'y'  # Wild Card
    },
    'Bears': {
        'name': 'Chicago Bears',
        'short_name': 'CHI',
        'division': 'NFC North',
        'conference': 'NFC',
        'logo_path': 'images/nfl/bears.png',
        'wins': 5,
        'losses': 12,
        'ties': 0,
        'win_pct': .294,
        'home_record': '4-5',
        'away_record': '1-7',
        'div_record': '1-5',
        'conf_record': '3-9',
        'points_for': 310,
        'points_against': 370,
        'point_diff': '-60',
        'streak': 'W1',
        'playoff_status': 'e'  # Eliminated
    },

    # NFC South
    'Buccaneers': {
        'name': 'Tampa Bay Buccaneers',
        'short_name': 'TB',
        'division': 'NFC South',
        'conference': 'NFC',
        'logo_path': 'images/nfl/buccaneers.png',
        'wins': 10,
        'losses': 7,
        'ties': 0,
        'win_pct': .588,
        'home_record': '5-4',
        'away_record': '5-3',
        'div_record': '4-2',
        'conf_record': '8-4',
        'points_for': 502,
        'points_against': 385,
        'point_diff': '+117',
        'streak': 'W2',
        'playoff_status': 'z'  # Clinched division
    },
    'Falcons': {
        'name': 'Atlanta Falcons',
        'short_name': 'ATL',
        'division': 'NFC South',
        'conference': 'NFC',
        'logo_path': 'images/nfl/falcons.png',
        'wins': 8,
        'losses': 9,
        'ties': 0,
        'win_pct': .471,
        'home_record': '4-5',
        'away_record': '4-4',
        'div_record': '4-2',
        'conf_record': '7-5',
        'points_for': 389,
        'points_against': 423,
        'point_diff': '-34',
        'streak': 'L2',
        'playoff_status': 'e'  # Eliminated
    },
    'Panthers': {
        'name': 'Carolina Panthers',
        'short_name': 'CAR',
        'division': 'NFC South',
        'conference': 'NFC',
        'logo_path': 'images/nfl/panthers.png',
        'wins': 5,
        'losses': 12,
        'ties': 0,
        'win_pct': .294,
        'home_record': '3-6',
        'away_record': '2-6',
        'div_record': '2-4',
        'conf_record': '4-8',
        'points_for': 341,
        'points_against': 534,
        'point_diff': '-193',
        'streak': 'W1',
        'playoff_status': 'e'  # Eliminated
    },
    'Saints': {
        'name': 'New Orleans Saints',
        'short_name': 'NO',
        'division': 'NFC South',
        'conference': 'NFC',
        'logo_path': 'images/nfl/saints.png',
        'wins': 5,
        'losses': 12,
        'ties': 0,
        'win_pct': .294,
        'home_record': '3-6',
        'away_record': '2-6',
        'div_record': '2-4',
        'conf_record': '4-8',
        'points_for': 338,
        'points_against': 398,
        'point_diff': '-60',
        'streak': 'L4',
        'playoff_status': 'e'  # Eliminated
    },

    # NFC West
    'Rams': {
        'name': 'Los Angeles Rams',
        'short_name': 'LAR',
        'division': 'NFC West',
        'conference': 'NFC',
        'logo_path': 'images/nfl/rams.png',
        'wins': 10,
        'losses': 7,
        'ties': 0,
        'win_pct': .588,
        'home_record': '5-4',
        'away_record': '5-3',
        'div_record': '4-2',
        'conf_record': '6-6',
        'points_for': 367,
        'points_against': 386,
        'point_diff': '-19',
        'streak': 'L1',
        'playoff_status': 'z'  # Clinched division
    },
    'Seahawks': {
        'name': 'Seattle Seahawks',
        'short_name': 'SEA',
        'division': 'NFC West',
        'conference': 'NFC',
        'logo_path': 'images/nfl/seahawks.png',
        'wins': 10,
        'losses': 7,
        'ties': 0,
        'win_pct': .588,
        'home_record': '3-6',
        'away_record': '7-1',
        'div_record': '4-2',
        'conf_record': '6-6',
        'points_for': 375,
        'points_against': 368,
        'point_diff': '+7',
        'streak': 'W2',
        'playoff_status': 'e'  # Eliminated
    },
    'Cardinals': {
        'name': 'Arizona Cardinals',
        'short_name': 'ARI',
        'division': 'NFC West',
        'conference': 'NFC',
        'logo_path': 'images/nfl/cardinals.png',
        'wins': 8,
        'losses': 9,
        'ties': 0,
        'win_pct': .471,
        'home_record': '6-3',
        'away_record': '2-6',
        'div_record': '3-3',
        'conf_record': '4-8',
        'points_for': 400,
        'points_against': 379,
        'point_diff': '+21',
        'streak': 'W1',
        'playoff_status': 'e'  # Eliminated
    },
    '49ers': {
        'name': 'San Francisco 49ers',
        'short_name': 'SF',
        'division': 'NFC West',
        'conference': 'NFC',
        'logo_path': 'images/nfl/49ers.png',
        'wins': 6,
        'losses': 11,
        'ties': 0,
        'win_pct': .353,
        'home_record': '4-5',
        'away_record': '2-6',
        'div_record': '1-5',
        'conf_record': '4-8',
        'points_for': 389,
        'points_against': 436,
        'point_diff': '-47',
        'streak': 'L4',
        'playoff_status': 'e'  # Eliminated
    }
}

NFL_DIVISIONS = {
    'AFC East': ['Bills', 'Dolphins', 'Jets', 'Patriots'],
    'AFC North': ['Ravens', 'Steelers', 'Bengals', 'Browns'],
    'AFC South': ['Texans', 'Colts', 'Jaguars', 'Titans'],
    'AFC West': ['Chiefs', 'Chargers', 'Broncos', 'Raiders'],
    'NFC East': ['Eagles', 'Commanders', 'Cowboys', 'Giants'],
    'NFC North': ['Lions', 'Vikings', 'Packers', 'Bears'],
    'NFC South': ['Buccaneers', 'Falcons', 'Panthers', 'Saints'],
    'NFC West': ['Rams', 'Seahawks', 'Cardinals', '49ers']
}
