# Defines the application components to be run as separate containers
services:

  # Define a service for web application
  StatVision:

    # Specify build options for the Docker image
    build:

      # Use the current directory as the build context
      context: ..

      # Use the specified Dockerfile to build the image
      dockerfile: Docker/Dockerfile

    # Specify entrypoint command to run on the django server
    entrypoint: ./Docker/entrypoint.sh

    environment:
      - GITHUB_SHA=${GITHUB_SHA}

    # Name the docker container
    container_name: statvision-container
    
    # Name the docker image
    image: statvision-image

    # Map port 80 on the host to port 5000 in the container
    ports:
      - "80:8000"

    # Mount the current directory to /home/docker in the container
    volumes:
      - ./..:/home/docker:ro
