# Defines the application components to be run as separate containers
services:

  # Define a service for web application
  StatVision:

    # Specify build options for the Docker image
    build:

      # Use the current directory as the build context
      context: .

      # Use the specified Dockerfile to build the image
      dockerfile: Dockerfile

    # Specify entrypoint command to run on the django server
    entrypoint: ./entrypoint.sh

    # Name the docker container
    container_name: statvision-container
    
    # Name the docker image
    image: statvision-image

    # Mount the current directory to /home/docker in the container
    volumes:
      - ./..:/home/docker
